package com.rivvana.naqos_app.auth.model.pencarian

data class Data(
    val address: String,
    val answer1: String,
    val answer2: String,
    val answer3: String,
    val city: City,
    val createdAt: Any,
    val description: String,
    val district: String,
    val facilities: List<Facility>,
    val id: String,
    val imageKosts: List<ImageKost>,
    val isAvailable: Boolean,
    val kostRating: Double,
    val kostType: String,
    val latitude: Double,
    val longitude: Double,
    val name: String,
    val ownerId: OwnerId,
    val postalCode: String,
    val pricePerDaily: Double,
    val pricePerMonthly: Double,
    val pricePerWeekly: Double,
    val question1: String,
    val question2: String,
    val question3: String,
    val rooms: List<Room>,
    val rules: String,
    val subdistrict: String,
    val updatedAt: Long
)